# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='counter',
            field=models.IntegerField(),
        ),
    ]
