# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redatabase', '0002_auto_20170416_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='counter',
        ),
    ]
