# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redatabase', '0005_note1'),
    ]

    operations = [
        migrations.CreateModel(
            name='smcoinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Formula', models.CharField(max_length=50)),
                ('Grainsize', models.CharField(max_length=50)),
                ('Latticeparameters', models.CharField(max_length=50)),
                ('Crystalstructure', models.CharField(max_length=50)),
            ],
        ),
    ]
