from django.db import models
from mongoengine import *
from django.contrib.auth.models import User

from pymongo import *
mongo=MongoClient('mongodb://localhost:27017/')
db=mongo['nanoscale']
db.add_user('ghaiyan','19941112qweaz',read_only=True)
db.add_user('haiyan','19941112qweaz',read_only=True)
smcoinformation=db['smcoinformation']
print('Number of Documents:')
print(smcoinformation.find().count())
def getone(smcoinformation):
    doc=smcoinformation.find_one()
    print('Single document:')
    print(doc)
def getMangFor(smcoinformation):
    print('\nMany Using While Loop:')
    cursor=smcoinformation.find()
    info=[]
    for doc in cursor:
        info.append(str(doc['Formula']))
        if len(info)>20:
            break
    print(info)
getone(smcoinformation)
getMangFor(smcoinformation)

class Note1(models.Model):
    user = models.ForeignKey(User)
    pub_date = models.DateTimeField()
    title = models.CharField(max_length=200)
    body = models.TextField()

    def __str__(self):
        return self.title

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __unicode__(self):
        return self.username


connect('nanoscale', host='127.0.0.1', port=27017) # 指明要连接的数据库

class users(Document):
    _id=StringField(max_length=100)
    id = IntField(max_length=10)
    title=StringField(max_length=100)
    first_name=StringField(max_length=50)
    middle_name=StringField(max_length=50)
    last_name=StringField(max_length=50)
    email=StringField(max_length=100)
    degree=StringField(max_length=50)
    orgination=StringField(max_length=100)
    country=StringField(max_length=50)
    city=StringField(max_length=50)
    admin=StringField(max_length=100)
    passwd=StringField(max_length=50)
    counter=IntField(max_length=200)
    meta = {'collection': 'users'}  # 指明连接数据库的哪张表



class smcoinformation(Document):
    _id = StringField(max_length=100)
    id=IntField(max_length=10)
    Formula=StringField(max_length=50)
    Grainsize=StringField(max_length=7)
    Latticeparameters=StringField(max_length=50)
    Crystalstructure=StringField(max_length=50)
    Phasetransformationtemperature=StringField(max_length=50)
    Debyetemperature=StringField(max_length=50)
    Curietemperature=StringField(max_length=50)
    Heatcapacity=StringField(max_length=50)
    Thermalexpansioncoefficient=StringField(max_length=50)
    Elasticmodulus=StringField(max_length=50)
    Saturationmagnetization=StringField(max_length=50)
    Remanence=StringField(max_length=50)
    Coercivity=StringField(max_length=50)
    max=StringField(max_length=50)
    def indertAll(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o):
        smcoinfo = smcoinformation(id=a, Formula=b, Grainsize=c, Latticeparameters=d, Crystalstructure=e,
                                   Phasetransformationtemperature=f, Debyetemperature=g, Curietemperature=h,
                                   Heatcapacity=i,Thermalexpansioncoefficient=j, Elasticmodulus=k, Saturationmagnetization=l,
                                   Remanence=m,Coercivity=n, max=o)
        smcoinfo.save()
    meta = {'collection': 'smcoinformation'}  # 指明连接数据库的哪张表

class cp_nano_smco(Document):
    id=IntField(maxLength=5)
    Temperature=IntField(maxLength=11)
    Sm2Co17HCP=StringField(max_length=100)
    SmCo2=StringField(max_length=100)
    SmCo3=StringField(max_length=100)
    Sm2Co7H=StringField(max_length=100)
    SmCo7=StringField(max_length=100)
    SmCo9_8=StringField(max_length=100)
    Sm2Co17R=StringField(max_length=100)
    Sm5Co2=StringField(max_length=100)
    Sm5Co19H=StringField(max_length=100)
    Sm5Co19R=StringField(max_length=100)
    Sm2Co7R=StringField(max_length=100)
    Sm3Co=StringField(max_length=100)
    meta = {'collection': 'cp_nano_smco'}  # 指明连接数据库的哪张表
class enthalpy_sm2co17hcp(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm2co17hcp'}  # 指明连接数据库的哪张表
class enthalpy_sm2co7h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm2co7h'}  # 指明连接数据库的哪张表
class enthalpy_sm2co7r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm2co7r'}  # 指明连接数据库的哪张表
class enthalpy_sm2co17r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm2co17r'}  # 指明连接数据库的哪张表
class enthalpy_sm3co(Document):
    Temperature=IntField(maxLength=11)
    _15nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm3co'}  # 指明连接数据库的哪张表
class enthalpy_sm5co19h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm5co19h'}  # 指明连接数据库的哪张表
class enthalpy_sm5co19r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm5co19r'}  # 指明连接数据库的哪张表
class enthalpy_sm9co4(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_sm9co4'}  # 指明连接数据库的哪张表
class enthalpy_smco2(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_smco2'}  # 指明连接数据库的哪张表
class enthalpy_smco3(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_smco3'}  # 指明连接数据库的哪张表
class enthalpy_smco5(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_smco5'}  # 指明连接数据库的哪张表
class enthalpy_smco7(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_smco7'}  # 指明连接数据库的哪张表
class enthalpy_smco9_8(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'enthalpy_smco9_8'}  # 指明连接数据库的哪张表
class entropy_sm2co7h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm2co7h'}  # 指明连接数据库的哪张表
class entropy_sm2co7r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm2co7r'}  # 指明连接数据库的哪张表
class entropy_sm2co17hcp(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm2co17hcp'}  # 指明连接数据库的哪张表
class entropy_sm2co17r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm2co17r'}  # 指明连接数据库的哪张表
class entropy_sm3co(Document):
    Temperature=IntField(maxLength=11)
    _15nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm3co'}  # 指明连接数据库的哪张表
class entropy_sm5co19h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm5co19h'}  # 指明连接数据库的哪张表
class entropy_sm5co19r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm5co19r'}  # 指明连接数据库的哪张表
class entropy_sm9co4(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_sm9co4'}  # 指明连接数据库的哪张表
class entropy_smco2(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_smco2'}  # 指明连接数据库的哪张表

class entropy_smco3(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_smco3'}  # 指明连接数据库的哪张表
class entropy_smco5(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_smco5'}  # 指明连接数据库的哪张表
class entropy_smco7(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_smco7'}  # 指明连接数据库的哪张表
class entropy_smco9_8(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'entropy_smco9_8'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm2co7h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm2co7h'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm2co7r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm2co7r'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm2co17hcp(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm2co17hcp'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm2co17r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm2co17r'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm3co(Document):
    Temperature=IntField(maxLength=11)
    _15nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm3co'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm5co19h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm5co19h'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm5co19r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm5co19r'}  # 指明连接数据库的哪张表
class gibbs_free_energy_sm9co4(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_sm9co4'}  # 指明连接数据库的哪张表
class gibbs_free_energy_smco2(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_smco2'}  # 指明连接数据库的哪张表
class gibbs_free_energy_smco3(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_smco3'}  # 指明连接数据库的哪张表
class gibbs_free_energy_smco5(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_smco5'}  # 指明连接数据库的哪张表
class gibbs_free_energy_smco7(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_smco7'}  # 指明连接数据库的哪张表
class gibbs_free_energy_smco9_8(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'gibbs_free_energy_smco9_8'}  # 指明连接数据库的哪张表
class grainsize_cp_sm2co7h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm2co7h'}  # 指明连接数据库的哪张表
class grainsize_cp_sm2co7r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm2co7r'}  # 指明连接数据库的哪张表
class grainsize_cp_sm2co17hcp(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm2co17hcp'}  # 指明连接数据库的哪张表
class grainsize_cp_sm2co17r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm2co17r'}  # 指明连接数据库的哪张表
class grainsize_cp_sm3co(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm3co'}  # 指明连接数据库的哪张表
class grainsize_cp_sm5co2(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm5co2'}  # 指明连接数据库的哪张表
class grainsize_cp_sm5co19h(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm5co19h'}  # 指明连接数据库的哪张表
class grainsize_cp_sm5co19r(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_sm5co19r'}  # 指明连接数据库的哪张表
class grainsize_cp_smco2(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_smco2'}  # 指明连接数据库的哪张表
class grainsize_cp_smco3(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_smco3'}  # 指明连接数据库的哪张表
class grainsize_cp_smco5(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_smco5'}  # 指明连接数据库的哪张表
class 	grainsize_cp_smco7(Document):
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': '	grainsize_cp_smco7'}  # 指明连接数据库的哪张表
class grainsize_cp_smco9_8(Document):
    _id = StringField(max_length=100)
    Temperature=IntField(maxLength=11)
    _10nm=StringField(max_length=255)
    _20nm = StringField(max_length=255)
    _30nm = StringField(max_length=255)
    _40nm = StringField(max_length=255)
    _50nm = StringField(max_length=255)
    _60nm = StringField(max_length=255)
    _70nm = StringField(max_length=255)
    _80nm = StringField(max_length=255)
    _90nm = StringField(max_length=255)
    _100nm = StringField(max_length=255)
    meta = {'collection': 'grainsize_cp_smco9_8'}  # 指明连接数据库的哪张表
class info_conductivity(Document):
    _id = StringField(max_length=100)
    ElementNumber=IntField(maxLength=11)
    MeasureTemperature=IntField(maxLength=11)
    Nd=StringField(max_length=255)
    Sm = StringField(max_length=255)
    Gd = StringField(max_length=255)
    Tb= StringField(max_length=255)
    Dy = StringField(max_length=255)
    Er = StringField(max_length=255)
    Tm= StringField(max_length=255)
    Ho = StringField(max_length=255)
    Sc= StringField(max_length=255)
    Y = StringField(max_length=255)
    Yb= StringField(max_length=255)
    La = StringField(max_length=255)
    Ce = StringField(max_length=255)
    Pr= StringField(max_length=255)
    Pm = StringField(max_length=255)
    Eu = StringField(max_length=255)
    Lu= StringField(max_length=255)
    meta = {'collection': 'info_conductivity'}  # 指明连接数据库的哪张表
class info_cp (Document):
    _id = StringField(max_length=100)
    MeasureTemperature = IntField(maxLength=11)
    Nd = StringField(max_length=255)
    Sm = StringField(max_length=255)
    Gd = StringField(max_length=255)
    Tb = StringField(max_length=255)
    Dy = StringField(max_length=255)
    Er = StringField(max_length=255)
    Tm = StringField(max_length=255)
    Ho = StringField(max_length=255)
    Sc = StringField(max_length=255)
    Y = StringField(max_length=255)
    Yb = StringField(max_length=255)
    La = StringField(max_length=255)
    Ce = StringField(max_length=255)
    Pr = StringField(max_length=255)
    Pm = StringField(max_length=255)
    Eu = StringField(max_length=255)
    Lu = StringField(max_length=255)
    meta = {'collection': 'info_cp'}  # 指明连接数据库的哪张表
class info_resistivity(Document):
    _id = StringField(max_length=100)
    MeasureTemperature = IntField(maxLength=11)
    Nd = StringField(max_length=255)
    Sm = StringField(max_length=255)
    Gd = StringField(max_length=255)
    Tb = StringField(max_length=255)
    Dy = StringField(max_length=255)
    Er = StringField(max_length=255)
    Tm = StringField(max_length=255)
    Ho = StringField(max_length=255)
    Sc = StringField(max_length=255)
    Y = StringField(max_length=255)
    Yb = StringField(max_length=255)
    La = StringField(max_length=255)
    Ce = StringField(max_length=255)
    Pr = StringField(max_length=255)
    Pm = StringField(max_length=255)
    Eu = StringField(max_length=255)
    Lu = StringField(max_length=255)
    meta = {'collection': 'info_resistivity'}  # 指明连接数据库的哪张表
class info_tec(Document):
    _id = StringField(max_length=100)
    MeasureTemperature = IntField(maxLength=11)
    Nd = StringField(max_length=255)
    Sm = StringField(max_length=255)
    Gd = StringField(max_length=255)
    Tb = StringField(max_length=255)
    Dy = StringField(max_length=255)
    Er = StringField(max_length=255)
    Tm = StringField(max_length=255)
    Ho = StringField(max_length=255)
    Sc = StringField(max_length=255)
    Y = StringField(max_length=255)
    Yb = StringField(max_length=255)
    La = StringField(max_length=255)
    Ce = StringField(max_length=255)
    Pr = StringField(max_length=255)
    Pm = StringField(max_length=255)
    Eu = StringField(max_length=255)
    Lu = StringField(max_length=255)
    meta = {'collection': 'info_tec'}  # 指明连接数据库的哪张表

class materialsinformation (Document):
    _id = StringField(max_length=100)
    MaterNumbers=IntField(max_length=11)
    MaterName=StringField(max_length=255)
    Structure=StringField(max_length=255)
    Size = StringField(max_length=255)
    TransPoint = StringField(max_length=255)
    MeasureTemperature= StringField(max_length=15)
    Resistivity = StringField(max_length=255)
    Conductivity = StringField(max_length=255)
    Cp= StringField(max_length=255)
    TEC =StringField(max_length=255)
    YModulus = StringField(max_length=255)
    Microhardness = StringField(max_length=255)
    Remark = StringField(max_length=255)
    def materialquery(self):
        count = materialsinformation.objects(Structure='Hexagonal').count()
        result = materialsinformation.objects(Structure='Hexagonal')
    meta = {'collection':'materialsinformation'}  # 指明连接数据库的哪张表
class note(Document):
    _id = StringField(max_length=100)
    Material=StringField(max_length=255)
    Preparation=StringField(max_length=255)
    Measuringtemperature=StringField(max_length=255)
    Grainsize = StringField(max_length=255)
    Phasetransformationtemperature = StringField(max_length=255)
    Electricalresistivity= StringField(max_length=255)
    Thermalconductivity = StringField(max_length=255)
    Heatcapacity = StringField(max_length=255)
    Thermalexpansioncoefficient= StringField(max_length=255)
    Elasticmodulus = StringField(max_length=255)
    Microhardness = StringField(max_length=255)
    Latticeparameters = StringField(max_length=255)
    Crystalstructure= StringField(max_length=255)
    Debyetemperature = StringField(max_length=255)
    Curietemperature = StringField(max_length=255)
    Mageticproperties= StringField(max_length=255)
    meta = {'collection': 'note'}  # 指明连接数据库的哪张表
class reference (Document):
    _id = StringField(max_length=100)
    id=IntField(maxLength=11)
    Authors = StringField(max_length=255)
    name= StringField(max_length=255)
    journal= StringField(max_length=255)
    Edited = StringField(max_length=255)
    press = StringField(max_length=255)
    volume= StringField(max_length=255)
    year= StringField(max_length=255)
    page = StringField(max_length=255)
    element = StringField(max_length=255)
    meta = {'collection': 'reference'}  # 指明连接数据库的哪张表

for i in reference.objects[:3]:
    print('element:',i.element)
for i in materialsinformation.objects[:3]:
    print('Structure:', i.Structure)
for i in info_conductivity.objects[:3]:
    print('MeasureTemperature:',i.MeasureTemperature)
for i in info_cp.objects[:3]:
    print('NdMeasure1:',i.Nd)
for i in info_resistivity.objects[:3]:
    print('NdMeasure2:',i.Nd)
for i in info_tec.objects[:3]:
    print('NdMeasure3:',i.Nd)
#class query():
count=materialsinformation.objects(Structure='Hexagonal').count()
result=	materialsinformation.objects(Structure='Hexagonal')
print(count)
print('these are materials whose structure is hexagonal')
for i in result:
    print(i.MaterName)
